require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe IdTypesController do

  # This should return the minimal set of attributes required to create a valid
  # IdType. As you add validations to IdType, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end
  
  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # IdTypesController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all id_types as @id_types" do
      id_type = IdType.create! valid_attributes
      get :index, {}, valid_session
      assigns(:id_types).should eq([id_type])
    end
  end

  describe "GET show" do
    it "assigns the requested id_type as @id_type" do
      id_type = IdType.create! valid_attributes
      get :show, {:id => id_type.to_param}, valid_session
      assigns(:id_type).should eq(id_type)
    end
  end

  describe "GET new" do
    it "assigns a new id_type as @id_type" do
      get :new, {}, valid_session
      assigns(:id_type).should be_a_new(IdType)
    end
  end

  describe "GET edit" do
    it "assigns the requested id_type as @id_type" do
      id_type = IdType.create! valid_attributes
      get :edit, {:id => id_type.to_param}, valid_session
      assigns(:id_type).should eq(id_type)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new IdType" do
        expect {
          post :create, {:id_type => valid_attributes}, valid_session
        }.to change(IdType, :count).by(1)
      end

      it "assigns a newly created id_type as @id_type" do
        post :create, {:id_type => valid_attributes}, valid_session
        assigns(:id_type).should be_a(IdType)
        assigns(:id_type).should be_persisted
      end

      it "redirects to the created id_type" do
        post :create, {:id_type => valid_attributes}, valid_session
        response.should redirect_to(IdType.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved id_type as @id_type" do
        # Trigger the behavior that occurs when invalid params are submitted
        IdType.any_instance.stub(:save).and_return(false)
        post :create, {:id_type => {}}, valid_session
        assigns(:id_type).should be_a_new(IdType)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        IdType.any_instance.stub(:save).and_return(false)
        post :create, {:id_type => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested id_type" do
        id_type = IdType.create! valid_attributes
        # Assuming there are no other id_types in the database, this
        # specifies that the IdType created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        IdType.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => id_type.to_param, :id_type => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested id_type as @id_type" do
        id_type = IdType.create! valid_attributes
        put :update, {:id => id_type.to_param, :id_type => valid_attributes}, valid_session
        assigns(:id_type).should eq(id_type)
      end

      it "redirects to the id_type" do
        id_type = IdType.create! valid_attributes
        put :update, {:id => id_type.to_param, :id_type => valid_attributes}, valid_session
        response.should redirect_to(id_type)
      end
    end

    describe "with invalid params" do
      it "assigns the id_type as @id_type" do
        id_type = IdType.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        IdType.any_instance.stub(:save).and_return(false)
        put :update, {:id => id_type.to_param, :id_type => {}}, valid_session
        assigns(:id_type).should eq(id_type)
      end

      it "re-renders the 'edit' template" do
        id_type = IdType.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        IdType.any_instance.stub(:save).and_return(false)
        put :update, {:id => id_type.to_param, :id_type => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested id_type" do
      id_type = IdType.create! valid_attributes
      expect {
        delete :destroy, {:id => id_type.to_param}, valid_session
      }.to change(IdType, :count).by(-1)
    end

    it "redirects to the id_types list" do
      id_type = IdType.create! valid_attributes
      delete :destroy, {:id => id_type.to_param}, valid_session
      response.should redirect_to(id_types_url)
    end
  end

end
